### ISSUE TITLE
Add Halle target

### ISSUE THREAD

**Issue by 3dfxatwork** [freifunk-berlin/buildbot#16]
Hi

please add the halle firmware builder for target ar71xx from https://github.com/FreifunkHalle/firmware-halle. It's forked from Freifunk/firmware-berlin, so commands are same. Please configure the build only when changes are applied.

**Comment by sarumpaet** [comment]
@3dfxatwork the last build was almost a year ago. Should we remove the Halle target?
http://buildbot.berlin.freifunk.net/builders/halle_ar71xx

**Comment by lynxis** [comment]
https://twitter.com/lynxislazus/status/737041513742503937

**Comment by lynxis** [comment]
let's wait some days and remove them. if they want to continue to use it, we can added quite easy.

**Comment by SvenRoederer** [comment]
think timeout reached ...
Maybe someone can check in person on the 33c3 with the Halle-guys
