### ISSUE TITLE
Remove old images

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/buildbot#27]
We should limit the number of kept binaries under `/usr/local/src/www/htdocs/buildbot/unstable/`. Current situation:
```
root@buildbot:/usr/local/src/www# df -h /usr/local/src/
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/Data-build  167G  159G  4.0K 100% /usr/local/src
```

**Comment by andrenarchy** [comment]
I removed a few old builds manually because the buildbot was unavailable. Wasn't there a script that cleans up the builds? :)

**Comment by booo** [comment]
There is a script in `/etc/cron.hourly`. I don't know why this does not work. I changed the path to rm, ls and tail. Maybe this is the problem?

**Comment by andrenarchy** [comment]
Works again, thx!
