### ISSUE TITLE
Rerun build with V=s -j1 on failure

### ISSUE THREAD

**Issue by sarumpaet** [freifunk-berlin/buildbot#28]
Currently it's almost impossible to see the reason for a failed build since logs end with a not very helpful "Please re-run make with -j1 V=s to see what's going on". Please change it so that this is done automatically.

**Comment by booo** [comment]
We could maybe upload the log files in `logs` instead of the firmware files. Maybe that is enough to debug?

**Comment by sarumpaet** [comment]
I don't see a logs/ directory when running a build locally. What logs are you referring to?
OTOH, is "make V=s -j12 || make V=s" such a problem? That would put the logs in, e.g., http://buildbot.berlin.freifunk.net/builders/ar71xx/builds/658/steps/shell_1/logs/stdio , where one would expect them.
