### ISSUE TITLE
build with different settings for a release-build

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/buildbot#33]
As discussed in the recent firmware-hacking event it seems good to trigger a build with different config when a release is ready. 
Config-settings like:
- Download-path of opkg-sources inside image
- upload-path of build images to firmware-server (not sure how this is done atm)
- not including the commit-hash in the filenames & OpenWRT-version

found that GitHub also supports a webhook-event when publishing a release (https://developer.github.com/v3/activity/events/types/#releaseevent)

so we can be triggered by "commits", as we d already, and also by relases. For sure we have to implement some changes in the firmware-Makefile for this to work (Env: REPO_PATH, IS_RELEASE).

affected issues:
- https://github.com/freifunk-berlin/firmware/issues/342
- https://github.com/freifunk-berlin/firmware/issues/337
- https://github.com/freifunk-berlin/buildbot/pull/32
- https://github.com/freifunk-berlin/buildbot/issues/24

**Comment by lynxis** [comment]
@SvenRoederer i'll setup a jenkins server doing:
* triggered by tags
* triggered by commits
* upload to a remote location

As well I'll sent a mail to the mailinglist describing why we should move to jenkins..

**Comment by SvenRoederer** [comment]
@lynxis for sure you can, but how does this fix this problem of this issue?

**Comment by lynxis** [comment]
@SvenRoederer because it's more flexible and allow tag builds for example.
