### ISSUE TITLE
HTTP-error 403 for new targets

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/buildbot#50]
a new target gives 403 error when trying to access the files.
 e.g. https://buildbot.berlin.freifunk.net/buildbot/unstable/ramips-mt76x8/

this seems to be very similar to issue #8

**Comment by SvenRoederer** [comment]
should this be covered by https://github.com/freifunk-berlin/buildbot/blob/master/masters/master/master.cfg#L126 or https://github.com/freifunk-berlin/buildbot/blob/master/masters/master/master.cfg#L143 ?

**Comment by booo** [comment]
Permissions a wrong on for the directory. I changed the permissions buy hand. A proper fix would be great.

```
root@buildbot:/usr/local/src/www/htdocs/buildbot/unstable# ll
total 36
drwxr-xr-x  9 buildbot buildbot 4096 May 24 05:58 ./
drwxr-xr-x  4 buildbot buildbot 4096 May 24 10:45 ../
drwxr-xr-x 21 buildbot buildbot 4096 May 24 06:17 ar71xx-generic/
drwxr-xr-x 21 buildbot buildbot 4096 May 23 23:17 ar71xx-mikrotik/
drwxr-xr-x 21 buildbot buildbot 4096 May 24 09:17 mpc85xx-generic/
drwxr-xr-x 21 buildbot buildbot 4096 May 24 10:17 ramips-mt7620/
drwxr-xr-x 21 buildbot buildbot 4096 May 24 10:17 ramips-mt7621/
drwx------  4 buildbot buildbot 4096 May 24 09:41 ramips-mt76x8/
drwxr-xr-x 21 buildbot buildbot 4096 May 24 08:17 x86-generic/
```

**Comment by SvenRoederer** [comment]
what is the umask, the build-master runs as?

**Comment by SvenRoederer** [comment]
please check https://github.com/freifunk-berlin/buildbot/commit/82fa9e2808224f94ae5ab1699582dba627965b18, as imho for releases we do not have this problem with bad permissions on the 1st-level subdirectory

**Comment by SvenRoederer** [comment]
this issue came up today for "ath79-generic" directory again.

Were you able to the for the change mentioned above?

**Comment by SvenRoederer** [comment]
@booo ath79-generic is still bad. Have you been able to test the mentioned change?

**Comment by booo** [comment]
As far as I can remember the change didn't fix the problem.

**Comment by booo** [comment]
I changed the permissions by hand again.

**Comment by SvenRoederer** [comment]
did you ran the commands as "buildbot-user"?

**Comment by SvenRoederer** [comment]
after merging d19e66b589d8bdcedf4148816322693eaae78cb0 this became an issue for new ipq-target

**Comment by sarumpaet** [comment]
The `-m` parameter of `mkdir` only applies to the last directory if `-p` is specified, so that doesn't work in this case. I just added a cronjob for the time being.

**Comment by SvenRoederer** [comment]
So it might help to run a ```chmod -R ``` after every build?

**Comment by sarumpaet** [comment]
A `chmod -R 755 /usr/local/src/www/htdocs/buildbot/` should do, yes.
