### ISSUE TITLE
master: Target directory permissions should be set to 755 and owned by www-data.buildbot

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/buildbot#62]
When a new architecture is added to the buildbot, then when the new directoy for that target is added, it has the wrong ownership and permissions.  The wrong permissions cause a "403 Forbidden" error.

For example
/usr/local/src/www/htdocs/buildbot/unstable/* were all created by the buildbot master script and had the wrong permissions.

This probaly also will happen when creating a new release in /usr/local/src/www/htdocs/buildbot/stable may also have the same problem.

**Comment by pmelange** [comment]
Permission should be set to 755

**Comment by SvenRoederer** [comment]
seems a dupe of https://github.com/freifunk-berlin/buildbot/issues/50

**Comment by pmelange** [comment]
Closing.  Please see #50
