### ISSUE TITLE
clicking "Rebuild" gives error "Cannot rebuild: invalid origin"

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/buildbot#64]
I tried to rebuild a failed build, and the result was "Cannot rebuild: invalid origin"

![79604273-10c2e000-80ee-11ea-9acc-0c6c9a0f3066](https://user-images.githubusercontent.com/20710446/79690226-a929a380-8259-11ea-8024-fe8ed3986573.png)

This issue was moved from https://github.com/freifunk-berlin/firmware/issues/786

Note, @SvenRoederer replied:
> on page http://buildbot.berlin.freifunk.net/#/builders/2/builds/27 works for me.
Btw. I think this should be reported in the buildbot repo, as it's not firmware related.

**Comment by flokli** [comment]
https://lists.buildbot.net/pipermail/users/2016-September/000712.html suggests this happens when `c['buildbotURL']` is misconfigured.
